name = "TiffImages"
uuid = "731e570b-9d59-4bfa-96dc-6df516fadf69"
authors = ["Tamas Nagy <github@tamasnagy.com>"]
version = "1.0.0"

[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
IndirectArrays = "9b13fd28-a010-5f03-acff-a1bbcff69959"
Inflate = "d25df0c9-e2be-5dd7-82c8-3ad0b3e990b9"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
PkgVersion = "eebad327-c553-4316-9ea0-9fa01ccd7688"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
SIMD = "fdea26ae-647d-5447-a871-4b548cad5224"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
ColorTypes = "0.10, 0.11"
DataStructures = "0.18"
DocStringExtensions = "0.8.3, 0.9"
FileIO = "1"
FixedPointNumbers = "0.8"
IndirectArrays = "0.5.1, 1"
Inflate = "0.1.4"
OffsetArrays = "1"
PkgVersion = "0.1.1, 0.3"
ProgressMeter = "1"
SIMD = "3.4.5"
julia = "1.6"
