[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DemoCards = "311a05b2-6137-4a5a-b473-18580a3d38b5"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
MappedArrays = "dbb5928d-eab1-5f90-85c2-b9b0edb7c900"
TiffImages = "731e570b-9d59-4bfa-96dc-6df516fadf69"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
